# Generated by Django 6.0.4 on 2026-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='totalHour',
            field=models.IntegerField(default=0),
        ),
    ]
