# Generated by Django 6.0.4 on 2026-04-20 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_volunteerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
